version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - .:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - laravel

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: myhata_db
      MYSQL_USER: myhata
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./src/storage/dbdata:/var/lib/mysql
    networks:
      - laravel

#  phpmyadmin:
#    image: "phpmyadmin:fpm-alpine"
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - "8080:80"
#    env_file:
#      - env/pma.env
#    networks:
#      - laravel

networks:
  laravel:

volumes:
  dbdata: