version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel

#  phpmyadmin:
#    image: "phpmyadmin:fpm-alpine"
#    container_name: phpmyadmin
#    restart: always
#    ports:
#      - "8080:80"
#    env_file:
#      - env/pma.env
#    networks:
#      - laravel

networks:
  laravel:
    name: laravel

volumes:
  dbdata:
    driver: local